export const GET_ALL_PAIEMENT = "GET_ALL_PAIEMENT";
export const SET_PAGINATE_PAIEMENT = "SET_PAGINATE_PAIEMENT";
export const POST_PAIEMENT = "POST_PAIEMENT";
export const PUT_PAIEMENT = "PUT_PAIEMENT";
export const DELETE_PAIEMENT = "DELETE_PAIEMENT";
export const DATA_EDIT_PAIEMENT = "DATA_EDIT_PAIEMENT";
export const SEARCH_PAIEMENT = "SEARCH_PAIEMENT";
export const PUT_VALIDATE_PAIEMENT = "PUT_VALIDATE_PAIEMENT"

 