export const GET_ALL_TRANSPORT = "GET_ALL_TRANSPORT";
export const SET_PAGINATE_TRANSPORT = "SET_PAGINATE_TRANSPORT";
export const POST_TRANSPORT = "POST_TRANSPORT";
export const PUT_TRANSPORT = "PUT_TRANSPORT";
export const DELETE_TRANSPORT = "DELETE_TRANSPORT";
